### ISSUE TITLE
Add terraspace version to image tags

### ISSUE THREAD

**Issue by gwvandesteeg** [boltops-tools/terraspace-dockerfiles#3]
Similarly to how certain other images are being released, can you add the Terraspace version number to the Docker tags so that people using these images can pin the use to a specific version of Terraspace.  Finding a CI/CD pipeline that failed because the Terraspace version has changed is not ideal.

**Comment by tongueroo** [comment]
Docs: https://terraspace.cloud/docs/install/docker/versioning/
